### ISSUE TITLE
numpy version if statement breaks for numpy 1.10

### ISSUE THREAD

**Issue by pettni** [tulip-control/polytope#20]
In numpy v. 1.6, `unique1d` was renamed to `unique`, which is taken care of in `quickhull.py` using an if statement. However, for numpy v. 1.10, the code on lines 49-50 give numpy_ver = 1.1, so it looks like numpy v. 1.1 is used.

Suggested fix:

1. Replace lines 49-50 with `numpy_ver = [int(s) for s in np.version.version.split('.')]`, and change if statements on lines 217 and 384 to lexicographic comparison: `if numpy_ver > [1,5,9]:`

2. Remove if statements and require numpy v. 1.6 or above

**Comment by johnyf** [comment]
The `if` statement in `polytope.quickhull` mentioned in the OP is [here](https://github.com/tulip-control/polytope/blob/ceb51452c944fef7fdca2acf34d439965bea25b9/polytope/quickhull.py#L217).

In Python, version comparison should conform to [PEP440](https://www.python.org/dev/peps/pep-0440/). This is more readily accomplished using `setuptools`, as discussed [here](http://stackoverflow.com/a/6972866/1959808).

Removing the selection constructs and requiring `numpy >= 1.6` seems a reasonable solution, because the latest `numpy == 1.10.1`. Please feel free to open a pull request.
